
include: package:flutter_lints/flutter.yaml

linter:

  rules:
    avoid_print: false
    avoid_relative_lib_imports: true
    always_use_package_imports: true
    require_trailing_commas: true
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    annotate_overrides: true
