name: rfid_inventory_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  auto_route: ^9.2.0
  hive: ^2.2.3
  path_provider: ^2.1.4
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  web_socket_channel: ^3.0.1
  gap: ^3.0.1
  shared_preferences: ^2.3.1
  flutter_staggered_grid_view: ^0.7.0
  material_tag_editor: ^0.1.2
  flex_color_picker: ^3.5.1
  uuid: ^4.4.2
  another_flushbar: ^1.12.30
  validator_regex: ^1.1.1
  image_picker: ^1.1.2
  firebase_core: ^2.24.2
  firebase_vertexai: ^0.1.1
  loader_overlay: ^4.0.1
  google_fonts: ^6.2.1
  permission_handler: ^11.3.1
  multi_select_flutter: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  flutter_gen_runner: ^5.6.0
  build_runner: ^2.4.11
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true
  assets:
    - assets/fonts/Open_Sans/static/
    - assets/fonts/Roboto/
    - assets/images/

